config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "users/registrations"}
  
  root "about#show"
  get "/index", to: "projects#index"
  resources :projects do
    resources :comments
    resources :projects_students, only:  [:create, :show]
  end

  get '/index' => "projects#index", :as => :user_root

  resource :users do
    resources :profiles
  end
  
  resources :transactions, only: [:create]
  get 'checkout/success', to: 'transactions#success'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, length: { minimum: 2, :message => "Message too short." }
  validates :body, presence: true
  belongs_to :project
  belongs_to :user
end

app/models/mentor.rb
class Mentor < User
    has_many :projects
    def mentor?
        true
    end
end

app/models/profile.rb
class Profile < ApplicationRecord
    belongs_to :user

    has_one_attached :avatar
end

app/models/project.rb
class Project < ApplicationRecord
    validates :project_description, length: { minimum: 10, :message => "Description too short." }
    validates :start_date, presence: true
    validate :date_validation
    has_many :comments, dependent: :destroy
    belongs_to :user
    has_many :projects_students
    has_many :students, { :through => :projects_students }

    def date_validation
        errors.add(:base, "End date cannot be before the starting date.") if end_date.before? start_date
    end
end

app/models/projects_student.rb
class ProjectsStudent < ApplicationRecord
    self.table_name = "projects_students"
    belongs_to :student
    belongs_to :project
end

app/models/student.rb
class Student < User
    has_many :projects_students
    has_many :projects, { :through => :projects_students }

    def student?
        true
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comments
  has_one :profile
  has_one_attached :avatar
  has_many :projects
  def mentor?
    false
  end

  def student?
    false
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def show
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

  
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:type, :first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:type, :first_name, :last_name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
    def create
        @project = Project.find(params[:project_id])
        @comment = @project.comments.create(comment_params)
        @comment.user = current_user
        @comment.save
        redirect_to project_path(@project)
    end

    def destroy
        @project = Project.find(params[:project_id])
        @comment = @project.comments.find(comment_params)
        @comment.destroy
        redirect_to project_path(@project)
    end
    private
    def comment_params
        params.require(:comment).permit(:user_id, :body)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    before_action :authenticate_user!
    def index
        @profiles = Profile.all
    end

    def new
        if current_user.profile.present?
            redirect_to index_path, notice: "You already have a profile!"
        else 
            @profile = Profile.new(:user_id => current_user)
        end
    end

    def create
        @user = current_user
        @profile = Profile.new(profile_params)
        @profile.user = current_user
        @profile.save
        redirect_to users_profile_path(current_user.profile.id)
    end

    def show
        @profile = Profile.find(params[:id])
    end

    def edit
        if current_user.profile == Profile.find(params[:id])
            @profile = current_user.profile
        else
            redirect_to users_profile_path, notice: "PERMISSION DENIED!"
        end
    end

    def update
        @profile = current_user.profile
        current_user.avatar.attach(profile_params[:avatar])
        if @profile.update(profile_params)
            redirect_to users_profile_path(current_user.profile.id)
        else
            render :show
        end
    end

    def profile_params
        params.require(:profile).permit(:about_me, :motivations, :interests, :background, :avatar)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    before_action :authenticate_user!
    def index
        @projects = Project.all
    end

    def show
        @project = Project.find(params[:id])
    end

    def new
        if current_user.type == 'Mentor'
            @project = Project.new
        else
            redirect_to index_path, notice: "ERROR: STUDENT'S CANNOT CREATE PROJECTS."
        end
    end

    def create
        @project = Project.new(project_params)
        @project.user = current_user

        if @project.save
            redirect_to @project
        else
            render :new
        end
    end

    def edit
        @project = Project.find(params[:id])
        if @project.user == current_user
            @project = Project.find(params[:id])
        else
            redirect_to project_path, notice: "PERMISSION DENIED!"
        end
    end

    def update
        @project = Project.find(params[:id])
        if @project.update(project_params)
            redirect_to @project
        else
            render :show
        end
    end

    def destroy
        @project = Project.find(params[:id])
        if current_user == @project.user
            @project.destroy
            redirect_to index_path
        else
            redirect_to project_path, notice: "PERMISSION DENIED!!!"
        end
    end

    private
    def project_params
        params.require(:project).permit(:project_name, :project_description, :start_date, :end_date, :project_id)
    end
end

app/controllers/projects_students_controller.rb
class ProjectsStudentsController < ApplicationController
    before_action :authenticate_user!
    def create
        if current_user.type == 'Student'
            @project = Project.find(params[:project_id])
                current_user.projects << @project
                render :template => 'projects/show'
        else 
            redirect_back fallback_location: { action: "show" }, notice: "ERROR, mentor accounts cannot enrol in projects!"
        end
    end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
    skip_before_action :verify_authenticity_token
    def create
        session = Stripe::Checkout::Session.create({
            payment_method_types: ['card'],
            line_items: [{
              price_data: {
                unit_amount: 500,
                currency: 'usd',
                product_data: {
                  name: 'Donate to Mentor',
                },
              },
              quantity: 1,
            }],
            mode: 'payment',
            success_url: checkout_success_url,
            cancel_url: index_url,
          })
        render json: { id: session.id }
    end

    def success

    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/projects_students_helper.rb
module ProjectsStudentsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/profiles/edit.html.erb
<section class="profile-form"> 
    <%= form_with model: [:users, @profile] do |f| %>
        <div>
            <%= f.label :avatar %>
            <%= f.file_field :avatar %>
        </div>

        <div class="field">
            <%= f.label :about_me %><br />
            <%= f.text_area :about_me, autofocus: true, autocomplete: "About Me" %>
        </div>

        <div class="field">
            <%= f.label :motivations %><br />
            <%= f.text_area :motivations, autofocus: true, autocomplete: "Motivations" %>
        </div>

        <div class="field">
            <%= f.label :interests %><br />
            <%= f.text_area :interests, autofocus: true, autocomplete: "Interests" %>
        </div>

        <div class="field">
            <%= f.label :background %><br />
            <%= f.text_area :background, autofocus: true, autocomplete: "Background" %>
        </div>

        <div class="actions">
            <%= f.submit "Save" %>
        </div>
    <% end %>
</section>

app/views/profiles/new.html.erb
<section class="profile-form">
    <%= form_with model: [:users, @profile] do |f| %>

        <div>
            <%= f.label :avatar %>
            <%= f.file_field :avatar %>
        </div>

        <div class="field">
            <%= f.label :about_me %><br />
            <%= f.text_area :about_me, autofocus: true, autocomplete: "About Me" %>
        </div>

        <div class="field">
            <%= f.label :motivations %><br />
            <%= f.text_area :motivations, autofocus: true, autocomplete: "Motivations" %>
        </div>

        <div class="field">
            <%= f.label :interests %><br />
            <%= f.text_area :interests, autofocus: true, autocomplete: "Interests" %>
        </div>

        <div class="field">
            <%= f.label :background %><br />
            <%= f.text_area :background, autofocus: true, autocomplete: "Background" %>
        </div>

        <div class="actions">
            <%= f.submit "Save" %>
        </div>
    <% end %>
</section>

app/views/profiles/show.html.erb
<section class="profile-card"> 
    <section class="profile-div">
        <div class="avatar">
        <% if @profile.avatar.present? %>
            <%= image_tag url_for(@profile.avatar), class: "avatar" %> 
        <% end %>
        <h1 class="profile-title"> <%= @profile.user.first_name + ' ' + @profile.user.last_name + ' - ' + @profile.user.type %> </h3>
        <% if current_user.profile == Profile.find(params[:id]) %>
            <%= link_to "Edit Profile", edit_users_profile_path, class: "profile-options" %>
        <% end %> 
        </div>
        <div class="text-div">
            <h1 class="prof"><strong>About Me</strong></h1>
            <p class="profile-text">
                <%= @profile.about_me %>
            </p>
            <h1 class="prof"><strong>Motivations</strong></h1>
            <p class="profile-text">
                <%= @profile.motivations %>
            </p>
            <h1 class="prof"><strong>Interests</strong></h1>
            <p class="profile-text">
                <%= @profile.interests %> 
            </p>
            <h1 class="prof"><strong>Background</strong></h1>
            <p class="profile-text">
                <%= @profile.background %> 
            </p>
        </div>
    </section>
</section>

app/views/projects/edit.html.erb
<section class="project-form">
  <div class="project-form">
    <h1>Edit your project</h1>

    <%= form_with model: @project do |form| %>
        <div class="project-form">
          <%= form.label :project_name %><br>
          <%= form.text_field :project_name%>
          <% @project.errors.full_messages_for(:title).each do |message| %>
            <div><%= message %></div>
          <% end %>
        </div>
      
        <div class="project-form">
          <%= form.label :project_description %><br>
          <%= form.text_area :project_description %><br>
          <% @project.errors.full_messages_for(:body).each do |message| %>
            <div><%= message %></div>
          <% end %>
        </div>

        <div class="project-form">
            <%= form.label :start_date %><br>
            <%= form.date_field :start_date %>
            <% @project.errors.full_messages_for(:current_date).each do |message| %>
            <div><%= message %></div>
            <% end %>
        </div>  
      
        <div class="project-form">
            <%= form.label :end_date, class: "project-form" %><br>
            <%= form.date_field :end_date %>
            <% @project.errors.full_messages_for(:current_date).each do |message| %>
                <div><%= message %></div>
            <% end %>
        </div>  
        <div class="project-form">
          <%= form.submit class: "edit-submit" %>
        </div>
      <% end %>
  </div>
</section>

app/views/projects/index.html.erb
<body>
    <section class="project-page">
        <div class="index">
                <% @projects.each do |project| %>
                    <div class="project-index">
                    <h3><%= link_to project.project_name, project %></h3>
                    <p><strong>Starting on: </strong><%= link_to project.start_date.strftime("%A %d %B %Y"), project %></p>
                    <% if project.user.profile.present?%>
                        <p><strong>Mentor -</strong> <%= link_to project.user.first_name + ' ' + project.user.last_name, users_profile_path(project.user.profile.id) %>
                        <% else %>
                        <strong>Mentor</strong> - <%= project.user.first_name + ' ' + project.user.last_name %>
                    <% end %>
                    </p>
                    </div>
            <% end %>
        </div>
                <div class="entry">
            <% if current_user.mentor? %>
                <button class="button"><%= link_to "Create New Project", new_project_path, class: "new-entry" %></button>
            <% end %>
        </div>
    </section>
</body>

app/views/projects/new.html.erb
<section class="project-form">
  <div class="project-form">
    <h1>Create a new project!</h1>

    <%= form_with model: @project do |form| %>
        <div class="project-form">
          <%= form.label :project_name %><br>
          <%= form.text_field :project_name%>
          <% @project.errors.full_messages_for(:title).each do |message| %>
            <div><%= message %></div>
          <% end %>
        </div>
      
        <div class="project-form">
          <%= form.label :project_description %><br>
          <%= form.text_area :project_description %><br>
          <% @project.errors.full_messages_for(:body).each do |message| %>
            <div><%= message %></div>
          <% end %>
        </div>

        <div class="project-form">
            <%= form.label :start_date %><br>
            <%= form.date_field :start_date %>
            <% @project.errors.full_messages_for(:current_date).each do |message| %>
            <div><%= message %></div>
            <% end %>
        </div>  
      
        <div class="project-form">
            <%= form.label :end_date, class: "project-form" %><br>
            <%= form.date_field :end_date %>
            <% @project.errors.full_messages_for(:current_date).each do |message| %>
                <div><%= message %></div>
            <% end %>
        </div>  
        <div class="project-form">
          <%= form.submit class:"project-form" %>
        </div>
      <% end %>
  </div>
</section>

app/views/projects/show.html.erb
<section class="show-page">
  <div class="project-show">
      <h3><%= @project.project_name %></h3>
      <p><strong>Mentor</strong> 
      <% if @project.user.profile.present? %>
        <%= link_to @project.user.first_name + ' ' + @project.user.last_name, users_profile_path(@project.user.profile.id) %>
      <% else %>
        <%= @project.user.first_name + ' ' + @project.user.last_name %>
      <% end %></p>
      <p class="proj-desc"><strong>Description </strong> <%= content_tag(:div, @project.project_description, class: "proj-desc") %> </p>
      <p><strong>Students</strong> </p> 
      <% @project.students.each do |students| %>
        <% if students.profile.present? %>
          <%= link_to students.first_name + ' ' + students.last_name, users_profile_path(students.profile.id) %>
          <br>
        <% else %>
          <%= students.first_name + ' ' + students.last_name %>
        <br>
        <% end %>
      <% end %>
  </p>
      <p>Begins: <%= @project.start_date.strftime("%A %d %B %Y") %> </p>
      <p>Ends: <%= @project.end_date.strftime("%A %d %B %Y")%> </p>
  </div>

  <div>
    <% if @project.students.where(:id => current_user.id).present? %>
      <strong>You are enrolled.</strong>
    <% elsif current_user.student? %>
      <%= link_to "Enrol", project_projects_students_path(@project), :method => :post, class: "show-buttons" %>
    <% end%>
   <button type="button" id="checkout-button" class="show-buttons">Donate $5</button>
  </div>

  <h2>Comments</h2>
  <% @project.comments.each do |comment| %>
    <p>
      <strong>
        <% if comment.user.profile.present? %>
          <%= link_to comment.user.first_name + " " + comment.user.last_name, users_profile_path(comment.user.profile.id) %>
        <% else%>
          <%= comment.user.first_name + " " + comment.user.last_name%>
        <% end %>
      </strong>
        <%= comment.created_at.strftime("%d/%m/%Y, %H:%M:%S %p") %>
    </p>
    <p>
      <%= comment.body %>
    </p>
  <% end %>


  <%= form_with model: [ @project, @project.comments.build ] do |form| %>

      <%= form.label 'Add a comment:' %></br>
      <%= form.text_area :body %>
    </p>
    <p>
      <%= form.submit %>
  </p>
  <% end %>

  <% if current_user.mentor? && @project.user == current_user %>
      <%= link_to "Edit", edit_project_path %>
  <% end %>

  <% if current_user.mentor? && @project.user == current_user %>
      <%= link_to "Delete", project_path(@project),
                      method: :delete,
                      data: { confirm: "Are you sure you want to delete this project?" } %>
  <% end %>
</section>

<script type="text/javascript">
    // Create an instance of the Stripe object with your publishable API key
    var stripe = Stripe("<%= Rails.application.credentials.dig(:stripe, :public_key) %>");

    var checkoutButton = document.getElementById("checkout-button");
    checkoutButton.addEventListener("click", function () {
      fetch("/transactions", {
        method: "POST",
      })
        .then(function (response) {
          return response.json();
        })
        .then(function (session) {
          return stripe.redirectToCheckout({ sessionId: session.id });
        })
        .then(function (result) {
          // If redirectToCheckout fails due to a browser or network
          // error, you should display the localized error message to your
          // customer using error.message.
          if (result.error) {
            alert(result.error.message);
          }
        })
        .catch(function (error) {
          console.error("Error:", error);
        });
    });
</script>