config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "users/registrations"}
  
  root "about#show"
  get "/index", to: "projects#index"
  resources :projects do
    resources :comments
    resources :projects_students, only:  [:create, :show]
  end

  get '/index' => "projects#index", :as => :user_root

  resource :users do
    resources :profiles
  end
  
  resources :transactions, only: [:create]
  get 'checkout/success', to: 'transactions#success'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, length: { minimum: 2, :message => "Message too short." }
  validates :body, presence: true
  belongs_to :project
  belongs_to :user
end

app/models/mentor.rb
class Mentor < User
    has_many :projects
    def mentor?
        true
    end
end

app/models/profile.rb
class Profile < ApplicationRecord
    belongs_to :user

    has_one_attached :avatar
end

app/models/project.rb
class Project < ApplicationRecord
    validates :project_description, length: { minimum: 10, :message => "Description too short." }
    validates :start_date, presence: true
    validate :date_validation
    has_many :comments, dependent: :destroy
    belongs_to :user
    has_many :projects_students
    has_many :students, { :through => :projects_students }

    def date_validation
        errors.add(:base, "End date cannot be before the starting date.") if end_date.before? start_date
    end
end

app/models/projects_student.rb
class ProjectsStudent < ApplicationRecord
    self.table_name = "projects_students"
    belongs_to :student
    belongs_to :project
end

app/models/student.rb
class Student < User
    has_many :projects_students
    has_many :projects, { :through => :projects_students }

    def student?
        true
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comments
  has_one :profile
  has_one_attached :avatar
  has_many :projects
  def mentor?
    false
  end

  def student?
    false
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def show
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

  
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:type, :first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:type, :first_name, :last_name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
    def create
        @project = Project.find(params[:project_id])
        @comment = @project.comments.create(comment_params)
        @comment.user = current_user
        @comment.save
        redirect_to project_path(@project)
    end

    def destroy
        @project = Project.find(params[:project_id])
        @comment = @project.comments.find(comment_params)
        @comment.destroy
        redirect_to project_path(@project)
    end
    private
    def comment_params
        params.require(:comment).permit(:user_id, :body)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    before_action :authenticate_user!
    def index
        @profiles = Profile.all
    end

    def new
        if current_user.profile.present?
            redirect_to index_path, notice: "You already have a profile!"
        else 
            @profile = Profile.new(:user_id => current_user)
        end
    end

    def create
        @user = current_user
        @profile = Profile.new(profile_params)
        @profile.user = current_user
        @profile.save
        redirect_to users_profile_path(current_user.profile.id)
    end

    def show
        @profile = Profile.find(params[:id])
    end

    def edit
        if current_user.profile == Profile.find(params[:id])
            @profile = current_user.profile
        else
            redirect_to users_profile_path, notice: "PERMISSION DENIED!"
        end
    end

    def update
        @profile = current_user.profile
        current_user.avatar.attach(profile_params[:avatar])
        if @profile.update(profile_params)
            redirect_to users_profile_path(current_user.profile.id)
        else
            render :show
        end
    end

    def profile_params
        params.require(:profile).permit(:about_me, :motivations, :interests, :background, :avatar)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    before_action :authenticate_user!
    def index
        @projects = Project.all
    end

    def show
        @project = Project.find(params[:id])
    end

    def new
        if current_user.type == 'Mentor'
            @project = Project.new
        else
            redirect_to index_path, notice: "ERROR: STUDENT'S CANNOT CREATE PROJECTS."
        end
    end

    def create
        @project = Project.new(project_params)
        @project.user = current_user

        if @project.save
            redirect_to @project
        else
            render :new
        end
    end

    def edit
        @project = Project.find(params[:id])
        if @project.user == current_user
            @project = Project.find(params[:id])
        else
            redirect_to project_path, notice: "PERMISSION DENIED!"
        end
    end

    def update
        @project = Project.find(params[:id])
        if @project.update(project_params)
            redirect_to @project
        else
            render :show
        end
    end

    def destroy
        @project = Project.find(params[:id])
        if current_user == @project.user
            @project.destroy
            redirect_to index_path
        else
            redirect_to project_path, notice: "PERMISSION DENIED!!!"
        end
    end

    private
    def project_params
        params.require(:project).permit(:project_name, :project_description, :start_date, :end_date, :project_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/projects_students_helper.rb
module ProjectsStudentsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>iMentor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://js.stripe.com/v3/"></script>
  </head>
<body>
  <nav class="navbar">
  <h1 class="imentor">iMentor</h1>
  <h3>
    <%= link_to "PROJECTS", index_path %>
    <%= link_to "ABOUT", root_path %>
  </h3>
      <div class="name-profile">
      <% if user_signed_in? %>
            <% if current_user.profile.present? %>
              <h3>
                <%= link_to current_user.first_name + ' ' + current_user.last_name, users_profile_path(current_user.profile.id) %>
              </h3>
            <% else %>
              <%= link_to link_to current_user.first_name + ' ' + current_user.last_name, new_users_profile_path, :method => :get %>
      <% end %>
      <h3>
          <%= link_to 'Account', edit_user_registration_path, class: "login-link" %> 
          <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "login-link" %>
            </div>
      </h3>
      <% else %>
      <div class="signup-profile">
        <h3 class="sign-up-acct">
          <%= link_to "Sign up", new_user_registration_path, class: "login-link" %> 
          <%= link_to "Login", new_user_session_path, class: "login-link" %>
        </h3>
      </div>
      <% end %>
  </nav>
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
  <%= yield %>
  </body>
</html>